version: '3.8'

services:
  product:
    image: product-service
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/toyota_m3
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: tulli2019
    depends_on:
      - db
      - naming

  naming:
    image: naming-server
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  auth:
    image: auth-service
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/toyota_m3
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: tulli2019
    depends_on:
      - db
      - naming

  sale:
    image: sale-service
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/toyota_m3
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: tulli2019
    depends_on:
      - db
      - naming

  api-gateway:
    image: gateway-service
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
    depends_on:
      - naming


  report:
    image: report-service
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - naming


  management:
    image: management-service
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - naming


  db:
    image: postgres
    platform: linux/amd64
    environment:
      POSTGRES_DB: toyota_m3
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tulli2019
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata:
